<?php

declare(strict_types=1);

/**
 * BillMySales for PrestaShop: es translations.
 *
 * Copyright (c) 2026 BillMySales <https://www.billmysales.com>
 * Licensed under the European Union Public Licence v. 1.2 (EUPL-1.2).
 * See LICENSE file for more details.
 *
 * Generated by scripts/i18n.php: do not edit the keys by hand, only the
 * translated (right-hand side) strings; then run scripts/i18n.php again
 * to fold in any source string change without losing them.
 */

global $_MODULE;
$_MODULE = [];
$_MODULE['<{billmysales}prestashop>billmysales_b44e5abab7e5fc3ce69be95c5bd3e561'] = 'BillMySales';
$_MODULE['<{billmysales}prestashop>billmysales_00feae087255b7c0b2d34e39f65b6024'] = 'Envía los pedidos a BillMySales cuando alcanzan los estados de pedido seleccionados, y agrega campos de facturación personalizados (p. ej. RUT, giro) al checkout.';
$_MODULE['<{billmysales}prestashop>billmysales_40a2cce01521763f35ce2ddef444f408'] = 'Esto detendrá la facturación automática a través de BillMySales.';
$_MODULE['<{billmysales}prestashop>billmysales_f298d60a512f809ab34620f6f8d70075'] = 'El envío a BillMySales está desactivado.';
$_MODULE['<{billmysales}prestashop>billmysales_364aa71f5dc5588e5a0a5b4363112a92'] = 'No se ha configurado la URL de notificación de BillMySales.';
$_MODULE['<{billmysales}prestashop>billmysales_018d963f1c49025140a70dac3b430a19'] = 'Configuración de notificaciones';
$_MODULE['<{billmysales}prestashop>billmysales_0c82fa8a0fea546c6235255141099fa8'] = 'Envíos';
$_MODULE['<{billmysales}prestashop>billmysales_b195eace6a1df586dc93cb56742fac65'] = 'La integración también debe estar activa en BillMySales para que los pedidos se envíen.';
$_MODULE['<{billmysales}prestashop>billmysales_4d3d769b812b6faa6b76e1a8abaece2d'] = 'Activo';
$_MODULE['<{billmysales}prestashop>billmysales_3cab03c00dbd11bc3569afa0748013f0'] = 'Inactivo';
$_MODULE['<{billmysales}prestashop>billmysales_a2b787ad97ab6f553dded04fc19dab01'] = 'URL de notificación';
$_MODULE['<{billmysales}prestashop>billmysales_ee9f47580caf7d30bde2bb534de363aa'] = 'La URL del webhook entregada por BillMySales.';
$_MODULE['<{billmysales}prestashop>billmysales_1e6947ac7fb3a9529a9726eb692c8cc5'] = 'Clave secreta';
$_MODULE['<{billmysales}prestashop>billmysales_bdefccb2c77e3109ab6bf94f3041077a'] = 'La clave secreta compartida con BillMySales, usada para firmar cada notificación.';
$_MODULE['<{billmysales}prestashop>billmysales_7888db3d73f96b37f680167fdf17a076'] = 'Formato de los datos';
$_MODULE['<{billmysales}prestashop>billmysales_80c7b621cccbb8624efb06d9ff899faf'] = '\"Estándar\" es lo que BillMySales procesa hoy. \"Webservice\" envía en cambio la representación del pedido propia del webservice de PrestaShop; úselo solo si su integración con BillMySales ya lo espera.';
$_MODULE['<{billmysales}prestashop>billmysales_eb6d8ae6f20283755b339c0dc273988b'] = 'Estándar';
$_MODULE['<{billmysales}prestashop>billmysales_a80d5e18649d829bda78450f7c862711'] = 'Webservice';
$_MODULE['<{billmysales}prestashop>billmysales_00096f58cc3265b0af5c4011e4ea533f'] = 'Estados de pedido que notifican';
$_MODULE['<{billmysales}prestashop>billmysales_798ec30eaaf5a96e50a9e5b8bc84fe68'] = 'BillMySales solo es notificado cuando un pedido alcanza uno de estos estados. Seleccione solo el estado que significa que el pago fue aceptado, para que un pedido no se envíe más de una vez.';
$_MODULE['<{billmysales}prestashop>billmysales_c9cc8cce247e49bae79f15173ce97354'] = 'Guardar';
$_MODULE['<{billmysales}prestashop>billmysales_7f8c0283f16925caed8e632086b81b9c'] = 'Enviado';
$_MODULE['<{billmysales}prestashop>billmysales_eb5e89bb0576ec498b968bebb4c21436'] = 'Reintentando';
$_MODULE['<{billmysales}prestashop>billmysales_ddfa35a73f20553b08b622f3982ed857'] = 'No enviado, sin más reintentos';
$_MODULE['<{billmysales}prestashop>billmysales_d37b1f6c0512e2118cee17fea015b699'] = 'Rechazado';
$_MODULE['<{billmysales}prestashop>configure_3f05f8c8c0828b6b426dcb3745fe100e'] = 'BillMySales envía sus pedidos a su plataforma de facturación cuando alcanzan el estado que usted elija, para que nunca tenga que facturarlos a mano.';
$_MODULE['<{billmysales}prestashop>configure_83706919f576717bd598f6f7215d3422'] = 'Más información en';
$_MODULE['<{billmysales}prestashop>configure_f4f70727dc34561dfde1a3c529b6205c'] = 'Configuración';
$_MODULE['<{billmysales}prestashop>configure_86c80b3438aaf080deed28e95023241c'] = 'Campos del checkout';
$_MODULE['<{billmysales}prestashop>custom_fields_86c80b3438aaf080deed28e95023241c'] = 'Campos del checkout';
$_MODULE['<{billmysales}prestashop>custom_fields_4978a12774c37a221ee1da02139e73fd'] = 'Estos campos se agregan al formulario de dirección del checkout (y a \"Mis direcciones\"), y se envían a BillMySales junto con el pedido.';
$_MODULE['<{billmysales}prestashop>custom_fields_ec34f72ad6ed94ed99871a6c6a5f2843'] = 'Agregar otro campo';
$_MODULE['<{billmysales}prestashop>custom_fields_21b7a1ed9c9b08a93cffc982400a0137'] = 'Guardar campos';
$_MODULE['<{billmysales}prestashop>custom_fields_row_b021df6aac4654c454f46c77646e745f'] = 'Etiqueta';
$_MODULE['<{billmysales}prestashop>custom_fields_row_4b1d20eb269e4d93c7ae2dc4ca0f3317'] = 'Ej: RUT, Razón social, Giro comercial';
$_MODULE['<{billmysales}prestashop>custom_fields_row_efeb782bc428be5cef6e02a858749ee5'] = 'Clave:';
$_MODULE['<{billmysales}prestashop>custom_fields_row_223381682a13779cab7cc9bbad1e31c7'] = 'Valores (opcional)';
$_MODULE['<{billmysales}prestashop>custom_fields_row_b88bfa3b70853744039a88545fea1017'] = 'Ej: Boleta, Factura';
$_MODULE['<{billmysales}prestashop>custom_fields_row_5cf1159440a98e12bb7dea26c2982eaa'] = 'Valores separados por coma muestran el campo como una lista de esas opciones; déjelo vacío para un campo de texto libre.';
$_MODULE['<{billmysales}prestashop>custom_fields_row_b651efdb98a5d6bd2b3935d0c3f4a5e2'] = 'Obligatorio';
$_MODULE['<{billmysales}prestashop>custom_fields_row_a15d71dcbf484a7ce682c5922ab747c8'] = 'El cliente debe completarlo para poder realizar el pedido.';
$_MODULE['<{billmysales}prestashop>custom_fields_row_9c1737eb7c43706b6673642689344d69'] = 'Eliminar este campo';
$_MODULE['<{billmysales}prestashop>order_block_b44e5abab7e5fc3ce69be95c5bd3e561'] = 'BillMySales';
$_MODULE['<{billmysales}prestashop>order_block_37899194093f7c0a1fdefe5431ad09cf'] = 'Estado del envío:';
$_MODULE['<{billmysales}prestashop>order_block_fe3591592e60bb29fca7f2232003bba7'] = 'Aún no enviado.';
$_MODULE['<{billmysales}prestashop>order_block_4dfd8c08d16df7766b8fda87c07336f9'] = 'Si este pedido no se realizó a través del checkout de la tienda (p. ej. se creó desde el back office), complete aquí los datos de facturación que BillMySales necesita.';
$_MODULE['<{billmysales}prestashop>order_block_fe0a49294d6dfd6c13ce312af9d536a2'] = '-- Seleccionar --';
$_MODULE['<{billmysales}prestashop>order_block_c9cc8cce247e49bae79f15173ce97354'] = 'Guardar';
$_MODULE['<{billmysales}prestashop>order_block_0d098162df0cf984573bcabea2d09b72'] = 'Enviar a BillMySales';
$_MODULE['<{billmysales}prestashop>order_create_fields_b44e5abab7e5fc3ce69be95c5bd3e561'] = 'BillMySales';
$_MODULE['<{billmysales}prestashop>order_create_fields_fe0a49294d6dfd6c13ce312af9d536a2'] = '-- Seleccionar --';
