<?php

declare(strict_types=1);

/**
 * BillMySales for PrestaShop.
 *
 * Copyright (c) 2026 BillMySales <https://www.billmysales.com>
 * Licensed under the European Union Public Licence v. 1.2 (EUPL-1.2).
 * See LICENSE file for more details.
 */

/**
 * Scans the plugin's source strings ($this->l('...') and the $translate()
 * callback in plugin/billmysales.php and plugin/src, {l s='...'
 * mod='billmysales'} in plugin/views/templates/admin/*.tpl) and updates
 * plugin/translations/es.php, keeping existing translations for unchanged
 * strings and reporting new or no-longer-used ones.
 *
 * PrestaShop's classic per-module translation format keys each string by
 * strtolower('<{'.$module_name.'}prestashop>'.$source).'_'.md5($string),
 * where $source is the module name for a $this->l() call and the calling
 * template's filename (without .tpl) for a Smarty {l} call (see
 * Translate::getModuleTranslation() and smartyTranslate() in PrestaShop's
 * core). Usage: php scripts/i18n.php
 */

const MODULE_NAME = 'billmysales';
const PLUGIN_DIR = __DIR__ . '/../plugin';
const CATALOG = PLUGIN_DIR . '/translations/es.php';

/**
 * A source string found in the plugin, and where it is used.
 */
final class Extracted
{
    /** @var string */
    public $source;

    /** @var string */
    public $string;

    /**
     * @param string $source The module name (PHP calls) or template basename (Smarty calls).
     * @param string $string The source (English) string.
     */
    public function __construct(string $source, string $string)
    {
        $this->source = $source;
        $this->string = $string;
    }

    /**
     * The classic system's array key for this string.
     *
     * @return string
     */
    public function key(): string
    {
        $normalized = preg_replace("/\\\\\\\\'/", "'", $this->string);
        return strtolower('<{' . MODULE_NAME . '}prestashop>' . $this->source) . '_' . md5((string) $normalized);
    }
}

/**
 * Extracts every $this->l('...') and $translate('...') call from a PHP file.
 *
 * @param string $file   File path.
 * @param string $source Source name (the module name).
 * @return Extracted[]
 */
function extract_php(string $file, string $source): array
{
    $code = (string) file_get_contents($file);
    $found = [];
    if (preg_match_all("/(?:\\\$this->l|\\\$translate)\\(\\s*'((?:[^'\\\\]|\\\\.)*)'/", $code, $matches)) {
        foreach ($matches[1] as $string) {
            $found[] = new Extracted($source, stripcslashes($string));
        }
    }
    return $found;
}

/**
 * Extracts every {l s='...' mod='billmysales'} call from a Smarty template.
 *
 * @param string $file File path.
 * @return Extracted[]
 */
function extract_tpl(string $file): array
{
    $code = (string) file_get_contents($file);
    $source = basename($file, '.tpl');
    $found = [];
    if (preg_match_all("/\\{l s='((?:[^'\\\\]|\\\\.)*)' mod='" . MODULE_NAME . "'\\}/", $code, $matches)) {
        foreach ($matches[1] as $string) {
            $found[] = new Extracted($source, stripcslashes($string));
        }
    }
    return $found;
}

/**
 * Loads the existing catalog's translations, by key.
 *
 * @param string $file Catalog file path.
 * @return array<string, string>
 */
function load_catalog(string $file): array
{
    if (!is_file($file)) {
        return [];
    }
    $_MODULE = [];
    include $file;
    return $_MODULE;
}

$extracted = array_merge(
    extract_php(PLUGIN_DIR . '/billmysales.php', MODULE_NAME),
    extract_php(PLUGIN_DIR . '/src/Admin/SettingsPage.php', MODULE_NAME),
    extract_php(PLUGIN_DIR . '/src/Admin/OrderBlock.php', MODULE_NAME)
);
foreach (glob(PLUGIN_DIR . '/views/templates/admin/*.tpl') ?: [] as $tpl) {
    $extracted = array_merge($extracted, extract_tpl($tpl));
}

$existing = load_catalog(CATALOG);
$used_keys = [];
$entries = [];
$new_count = 0;
foreach ($extracted as $item) {
    $key = $item->key();
    if (isset($used_keys[$key])) {
        continue;
    }
    $used_keys[$key] = true;
    if (isset($existing[$key])) {
        $entries[$key] = $existing[$key];
    } else {
        $entries[$key] = '';
        ++$new_count;
        fwrite(STDERR, "new: [{$item->source}] {$item->string}\n");
    }
}
foreach ($existing as $key => $value) {
    if (!isset($used_keys[$key])) {
        fwrite(STDERR, "unused (removed): {$key}\n");
    }
}

$lines = [
    '<?php',
    '',
    'declare(strict_types=1);',
    '',
    '/**',
    ' * BillMySales for PrestaShop: es translations.',
    ' *',
    ' * Copyright (c) 2026 BillMySales <https://www.billmysales.com>',
    ' * Licensed under the European Union Public Licence v. 1.2 (EUPL-1.2).',
    ' * See LICENSE file for more details.',
    ' *',
    ' * Generated by scripts/i18n.php: do not edit the keys by hand, only the',
    ' * translated (right-hand side) strings; then run scripts/i18n.php again',
    " * to fold in any source string change without losing them.",
    ' */',
    '',
    'global $_MODULE;',
    '$_MODULE = [];',
];
foreach ($entries as $key => $value) {
    $lines[] = "\$_MODULE['" . addslashes($key) . "'] = '" . addslashes($value) . "';";
}
$lines[] = '';

file_put_contents(CATALOG, implode("\n", $lines));
fwrite(STDERR, sprintf("%d strings, %d new, %d in %s\n", count($entries), $new_count, count($entries), CATALOG));
