<?php

declare(strict_types=1);

/**
 * Applies scripts/i18n-es.php's translations onto
 * plugin/translations/es.php's keys (run after scripts/i18n.php has
 * (re)scanned the plugin's source strings). Part of `make i18n`.
 */

function make_key(string $source, string $string): string
{
    $normalized = preg_replace("/\\\\\\\\'/", "'", $string);
    return strtolower('<{billmysales}prestashop>' . $source) . '_' . md5((string) $normalized);
}

$map = include __DIR__ . '/i18n-es.php';
$out = [];
foreach ($map as $source => $strings) {
    foreach ($strings as $en => $es) {
        $out[make_key((string) $source, (string) $en)] = $es;
    }
}

$_MODULE = [];
include __DIR__ . '/../plugin/translations/es.php';
$existing = $_MODULE;

$missing = 0;
foreach ($existing as $k => $v) {
    if (!isset($out[$k])) {
        echo "MISSING TRANSLATION for key not in map: {$k}\n";
        ++$missing;
    }
}
echo 'total existing keys: ' . count($existing) . ', mapped: ' . count($out) . ", missing: {$missing}\n";

$lines = [
    '<?php',
    '',
    'declare(strict_types=1);',
    '',
    '/**',
    ' * BillMySales for PrestaShop: es translations.',
    ' *',
    ' * Copyright (c) 2026 BillMySales <https://www.billmysales.com>',
    ' * Licensed under the European Union Public Licence v. 1.2 (EUPL-1.2).',
    ' * See LICENSE file for more details.',
    ' *',
    ' * Generated by scripts/i18n.php: do not edit the keys by hand, only the',
    ' * translated (right-hand side) strings; then run scripts/i18n.php again',
    ' * to fold in any source string change without losing them.',
    ' */',
    '',
    'global $_MODULE;',
    '$_MODULE = [];',
];
foreach ($existing as $k => $v) {
    $val = $out[$k] ?? $v;
    $lines[] = '$_MODULE[\'' . addslashes((string) $k) . '\'] = \'' . addslashes((string) $val) . '\';';
}
$lines[] = '';

file_put_contents(__DIR__ . '/../plugin/translations/es.php', implode("\n", $lines));
echo "written\n";
